// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAI814xogkD9nilRlmVSRpB0FKWcpPpgoU',
    appId: '1:554491010594:web:4ea9f6f6ae684edbbc747b',
    messagingSenderId: '554491010594',
    projectId: 'lecture10-82f37',
    authDomain: 'lecture10-82f37.firebaseapp.com',
    storageBucket: 'lecture10-82f37.firebasestorage.app',
    measurementId: 'G-TBGB6JNEW6',
    databaseURL: "https://lecture10-82f37-default-rtdb.firebaseio.com"
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoLvJbByVLNDTTCuHnlmMPWqUyCe3_PSA',
    appId: '1:554491010594:android:ef4658c73bede99abc747b',
    messagingSenderId: '554491010594',
    projectId: 'lecture10-82f37',
    storageBucket: 'lecture10-82f37.firebasestorage.app',
    databaseURL: "https://lecture10-82f37-default-rtdb.firebaseio.com"
    )
  ;

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClnnIkK1nHzToCfBU4Sl7lZIZ7pxu_Noo',
    appId: '1:554491010594:ios:c9752ef8a2659056bc747b',
    messagingSenderId: '554491010594',
    projectId: 'lecture10-82f37',
    storageBucket: 'lecture10-82f37.firebasestorage.app',
    iosBundleId: 'com.example.lecture10firebaseDb',
    databaseURL: "https://lecture10-82f37-default-rtdb.firebaseio.com"
  );
}
